services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - "9200:9200"
    networks:
      - log_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - log_data:/logs:ro
    depends_on:
      - elasticsearch
      - log-generator
    networks:
      - log_network

  log-generator:
    build: ./log-generator
    volumes:
      - log_data:/logs
    networks:
      - log_network

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    networks:
      - log_network
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    networks:
      - log_network
    command: >
      sh -c "while ! curl -s http://ollama:11434/api/tags > /dev/null; do echo 'Waiting for Ollama to be available...'; sleep 5; done; echo 'Ollama is up, pulling llama3...'; curl -X POST http://ollama:11434/api/pull -d '{\"name\":\"llama3\"}'; echo 'Model pulled successfully.';"

  django-app:
    build: ./django-app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - ollama
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - OLLAMA_HOST=http://ollama:11434
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=d.logmonitoring@gmail.com
      - SMTP_PASSWORD=brmabvqlziayqtof   # remove spaces
      - ALERT_EMAIL_FROM=d.logmonitoring@gmail.com
      - ALERT_EMAIL_TO=hariprasath475767@gmail.com
    networks:
      - log_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - log_network

networks:
  log_network:
    driver: bridge

volumes:
  ollama_data:
  log_data:
