filebeat.inputs:
- type: filestream
  id: multi-server-logs
  enabled: true
  paths:
    - /logs/server_*.log
  parsers:
    - ndjson:
        target: ""
        overwrite_keys: true
        add_error_key: true
  fields:
    log_type: server
  fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]